import "dotenv/config";
import { prisma } from "./lib/prisma.js";

async function seed() {
  console.log("Seeding 50 real vehicle records with accurate Unsplash imagery...");

  // Clear existing purchases and vehicles for clean re-seed
  await prisma.purchase.deleteMany();
  await prisma.vehicle.deleteMany();

  const vehiclesData = [
    // 1 - 10: Popular Sedans & Luxury Sedans
    {
      make: "Toyota",
      model: "Camry LE Hybrid",
      category: "SEDAN" as const,
      year: 2024,
      fuelType: "HYBRID" as const,
      color: "Celestial Silver",
      transmission: "AUTOMATIC" as const,
      price: 28850,
      quantity: 8,
      description: "Fuel-efficient midsize hybrid sedan offering 52 MPG rating, Toyota Safety Sense 3.0, and smooth ride quality.",
      imageUrl: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Honda",
      model: "Accord Touring",
      category: "SEDAN" as const,
      year: 2024,
      fuelType: "HYBRID" as const,
      color: "Platinum White",
      transmission: "AUTOMATIC" as const,
      price: 38890,
      quantity: 6,
      description: "Sleek executive hybrid sedan featuring 12.3-inch touchscreen, Google Built-in, and Bose 12-speaker audio system.",
      imageUrl: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Tesla",
      model: "Model 3 Long Range",
      category: "SEDAN" as const,
      year: 2024,
      fuelType: "ELECTRIC" as const,
      color: "Deep Blue Metallic",
      transmission: "AUTOMATIC" as const,
      price: 42490,
      quantity: 9,
      description: "All-electric performance sedan delivering 341 miles of EPA range, dual-motor AWD, and Autopilot capability.",
      imageUrl: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "BMW",
      model: "330i xDrive",
      category: "SEDAN" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Jet Black",
      transmission: "AUTOMATIC" as const,
      price: 46500,
      quantity: 5,
      description: "Iconic sport sedan powered by 255-hp TwinPower Turbo engine with xDrive intelligent all-wheel drive.",
      imageUrl: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Audi",
      model: "A6 45 TFSI quattro",
      category: "SEDAN" as const,
      year: 2024,
      fuelType: "HYBRID" as const,
      color: "Mythos Black",
      transmission: "AUTOMATIC" as const,
      price: 58100,
      quantity: 4,
      description: "Executive luxury sedan with mild-hybrid technology, dual MMI touch response displays, and quattro AWD.",
      imageUrl: "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Mercedes-Benz",
      model: "C 300 4MATIC",
      category: "SEDAN" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Polar White",
      transmission: "AUTOMATIC" as const,
      price: 48850,
      quantity: 6,
      description: "Elegant luxury sedan featuring mild-hybrid turbo engine, 11.9-inch portrait touchscreen, and ambient interior lighting.",
      imageUrl: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Lexus",
      model: "ES 350 Ultra Luxury",
      category: "SEDAN" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Eminent White",
      transmission: "AUTOMATIC" as const,
      price: 51230,
      quantity: 5,
      description: "Remarkably quiet luxury sedan powered by 302-hp V6 engine with semi-aniline leather upholstery.",
      imageUrl: "https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Genesis",
      model: "G80 3.5T Sport",
      category: "SEDAN" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Makalu Gray",
      transmission: "AUTOMATIC" as const,
      price: 65500,
      quantity: 3,
      description: "Distinctive luxury sedan boasting twin-turbo V6 engine, rear-wheel steering, and Nappa leather seating.",
      imageUrl: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Porsche",
      model: "Panamera GTS",
      category: "SEDAN" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Carmine Red",
      transmission: "AUTOMATIC" as const,
      price: 135500,
      quantity: 2,
      description: "High-performance luxury sedan equipped with twin-turbo V8 producing 473-hp and adaptive air suspension.",
      imageUrl: "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Lucid",
      model: "Air Grand Touring",
      category: "SEDAN" as const,
      year: 2024,
      fuelType: "ELECTRIC" as const,
      color: "Stellar White",
      transmission: "AUTOMATIC" as const,
      price: 109900,
      quantity: 3,
      description: "Ultra-luxury electric sedan with 819 horsepower, 516 miles of range, and 900V ultra-fast charging.",
      imageUrl: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&auto=format&fit=crop&q=80",
    },

    // 11 - 20: SUVs & Crossovers
    {
      make: "Honda",
      model: "CR-V EX-L",
      category: "SUV" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Pearl White",
      transmission: "AUTOMATIC" as const,
      price: 34650,
      quantity: 7,
      description: "Spacious crossover SUV featuring leather interior, power tailgate, and wireless Apple CarPlay.",
      imageUrl: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Toyota",
      model: "RAV4 Prime XSE",
      category: "SUV" as const,
      year: 2024,
      fuelType: "HYBRID" as const,
      color: "Magnetic Gray",
      transmission: "AUTOMATIC" as const,
      price: 47560,
      quantity: 6,
      description: "302-hp plug-in hybrid SUV with 42 miles of pure EV driving range and electronic all-wheel drive.",
      imageUrl: "https://images.unsplash.com/photo-1581540222194-0def2dda95b8?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Tesla",
      model: "Model Y Performance",
      category: "SUV" as const,
      year: 2024,
      fuelType: "ELECTRIC" as const,
      color: "Solid Black",
      transmission: "AUTOMATIC" as const,
      price: 52490,
      quantity: 8,
      description: "All-electric crossover accelerating 0-60 mph in 3.5 seconds with 279 miles of range and dual motors.",
      imageUrl: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Mercedes-Benz",
      model: "GLE 350 4MATIC",
      category: "SUV" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Emerald Green",
      transmission: "AUTOMATIC" as const,
      price: 62650,
      quantity: 4,
      description: "Prestige luxury SUV providing plush air suspension, MBUX AI assistant, and panorama sunroof.",
      imageUrl: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "BMW",
      model: "X5 xDrive40i",
      category: "SUV" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Mineral White",
      transmission: "AUTOMATIC" as const,
      price: 67500,
      quantity: 5,
      description: "Luxury midsize SAV powered by 375-hp TwinPower turbo inline 6-cylinder engine with curved digital display.",
      imageUrl: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Porsche",
      model: "Cayenne S",
      category: "SUV" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Chalk",
      transmission: "AUTOMATIC" as const,
      price: 95700,
      quantity: 3,
      description: "Dynamic performance SUV equipped with twin-turbo V8 delivering 468 horsepower and sport chrono package.",
      imageUrl: "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Hyundai",
      model: "Ioniq 5 Limited",
      category: "SUV" as const,
      year: 2024,
      fuelType: "ELECTRIC" as const,
      color: "Cyber Gray",
      transmission: "AUTOMATIC" as const,
      price: 53500,
      quantity: 7,
      description: "Futuristic electric CUV with ultra-fast 800V charging capability and relaxation driver seat.",
      imageUrl: "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Kia",
      model: "EV6 GT AWD",
      category: "SUV" as const,
      year: 2024,
      fuelType: "ELECTRIC" as const,
      color: "Runway Red",
      transmission: "AUTOMATIC" as const,
      price: 61600,
      quantity: 4,
      description: "576-horsepower high-performance electric crossover capable of 0-60 mph in 3.4 seconds.",
      imageUrl: "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Jeep",
      model: "Grand Cherokee Summit",
      category: "SUV" as const,
      year: 2024,
      fuelType: "HYBRID" as const,
      color: "Velvet Red",
      transmission: "AUTOMATIC" as const,
      price: 65200,
      quantity: 4,
      description: "Luxury 4x4 SUV with 4xe plug-in hybrid powertrain, Palermo leather interior, and McIntosh audio system.",
      imageUrl: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Cadillac",
      model: "Escalade ESV Sport Platinum",
      category: "SUV" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Black Raven",
      transmission: "AUTOMATIC" as const,
      price: 112690,
      quantity: 2,
      description: "Full-size flagship SUV featuring 38-inch curved OLED screen, Super Cruise hands-free driving, and AKG 36-speaker sound.",
      imageUrl: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&auto=format&fit=crop&q=80",
    },

    // 21 - 30: Sports Coupes & Supercars
    {
      make: "Porsche",
      model: "911 Carrera S",
      category: "COUPE" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Guards Red",
      transmission: "AUTOMATIC" as const,
      price: 131300,
      quantity: 2,
      description: "Iconic rear-engine sports car delivering 443 horsepower from twin-turbo 3.0L boxer-6 engine.",
      imageUrl: "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Chevrolet",
      model: "Corvette Z06",
      category: "COUPE" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Torch Red",
      transmission: "AUTOMATIC" as const,
      price: 112700,
      quantity: 2,
      description: "670-hp naturally aspirated 5.5L flat-plane crank V8 supercar capable of 8,600 RPM redline.",
      imageUrl: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Audi",
      model: "R8 V10 Performance",
      category: "COUPE" as const,
      year: 2023,
      fuelType: "PETROL" as const,
      color: "Vegas Yellow",
      transmission: "AUTOMATIC" as const,
      price: 158600,
      quantity: 1,
      description: "Naturally aspirated 602-hp 5.2L V8 supercar with quattro all-wheel drive and carbon ceramic brakes.",
      imageUrl: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Ford",
      model: "Mustang Dark Horse",
      category: "COUPE" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Blue Ember",
      transmission: "MANUAL" as const,
      price: 59270,
      quantity: 4,
      description: "Track-focused muscle car with 500-hp 5.0L Coyote V8 engine, TREMEC 6-speed manual, and MagneRide suspension.",
      imageUrl: "https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "BMW",
      model: "M4 Competition xDrive",
      category: "COUPE" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Isle of Man Green",
      transmission: "AUTOMATIC" as const,
      price: 86300,
      quantity: 3,
      description: "503-horsepower twin-turbo inline 6 sports coupe with carbon bucket seats and M xDrive AWD system.",
      imageUrl: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Nissan",
      model: "Z Nismo",
      category: "COUPE" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Stealth Gray",
      transmission: "AUTOMATIC" as const,
      price: 64990,
      quantity: 3,
      description: "420-hp twin-turbo V6 performance coupe featuring NISMO tuned suspension, Recaro seats, and enhanced cooling.",
      imageUrl: "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Toyota",
      model: "GR Supra 3.0 Premium",
      category: "COUPE" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Renaissance Red",
      transmission: "MANUAL" as const,
      price: 57650,
      quantity: 4,
      description: "382-hp 3.0L turbocharged inline-6 sports coupe featuring a 6-speed intelligent manual transmission.",
      imageUrl: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Aston Martin",
      model: "Vantage V8 Coupe",
      category: "COUPE" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Aston Martin Racing Green",
      transmission: "AUTOMATIC" as const,
      price: 143900,
      quantity: 2,
      description: "British twin-turbo 4.0L V8 sports car producing 503 hp with electronic rear differential and quad exhausts.",
      imageUrl: "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Mercedes-AMG",
      model: "GT 55 4MATIC+",
      category: "COUPE" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Hyper Blue",
      transmission: "AUTOMATIC" as const,
      price: 134900,
      quantity: 2,
      description: "Grand touring 469-hp twin-turbo V8 coupe featuring active roll stabilization and rear-axle steering.",
      imageUrl: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Lexus",
      model: "LC 500 Bespoke Build",
      category: "COUPE" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Infrared Red",
      transmission: "AUTOMATIC" as const,
      price: 99800,
      quantity: 2,
      description: "Naturally aspirated 471-hp 5.0L V8 grand tourer with carbon fiber roof and Yamaha performance dampers.",
      imageUrl: "https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&auto=format&fit=crop&q=80",
    },

    // 31 - 40: Hatchbacks, Wagons & Convertibles
    {
      make: "Volkswagen",
      model: "Golf GTI SE",
      category: "HATCHBACK" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Tornado Red",
      transmission: "MANUAL" as const,
      price: 31995,
      quantity: 6,
      description: "The definitive hot hatch combining 241-hp turbo engine, manual gearbox, and plaid cloth seating.",
      imageUrl: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Honda",
      model: "Civic Type R",
      category: "HATCHBACK" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Championship White",
      transmission: "MANUAL" as const,
      price: 44795,
      quantity: 3,
      description: "315-hp turbocharged VTEC hot hatch featuring Brembo brakes, limited-slip differential, and rear wing.",
      imageUrl: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Toyota",
      model: "GR Corolla Circuit Edition",
      category: "HATCHBACK" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Heavy Metal Gray",
      transmission: "MANUAL" as const,
      price: 45140,
      quantity: 3,
      description: "Rally-inspired 300-hp 3-cylinder turbo hatchback equipped with GR-FOUR adjustable AWD system.",
      imageUrl: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Subaru",
      model: "Outback Touring XT",
      category: "WAGON" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Autumn Green",
      transmission: "AUTOMATIC" as const,
      price: 42795,
      quantity: 6,
      description: "260-hp turbocharged all-weather wagon featuring symmetrical AWD, Nappa leather, and EyeSight safety.",
      imageUrl: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Audi",
      model: "RS 6 Avant Performance",
      category: "WAGON" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Nardo Gray",
      transmission: "AUTOMATIC" as const,
      price: 126800,
      quantity: 2,
      description: "621-hp twin-turbo V8 super wagon with dynamic ride control suspension and RS sport exhaust.",
      imageUrl: "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Volvo",
      model: "V90 Cross Country Ultimate",
      category: "WAGON" as const,
      year: 2024,
      fuelType: "HYBRID" as const,
      color: "Crystal White",
      transmission: "AUTOMATIC" as const,
      price: 65400,
      quantity: 4,
      description: "Scandinavian luxury mild-hybrid wagon featuring Bowers & Wilkins high-fidelity sound and Google infotainment.",
      imageUrl: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Chevrolet",
      model: "Corvette Stingray Convertible",
      category: "CONVERTIBLE" as const,
      year: 2023,
      fuelType: "PETROL" as const,
      color: "Rapid Blue",
      transmission: "AUTOMATIC" as const,
      price: 76900,
      quantity: 2,
      description: "495-hp mid-engine V8 American supercar with power hardtop convertible roof opening in 16 seconds.",
      imageUrl: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Porsche",
      model: "718 Boxster GTS 4.0",
      category: "CONVERTIBLE" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Python Green",
      transmission: "MANUAL" as const,
      price: 97300,
      quantity: 2,
      description: "Naturally aspirated 394-hp 4.0L flat-6 roadster offering mid-engine agility and open-air thrills.",
      imageUrl: "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "BMW",
      model: "Z4 M40i Handschalter",
      category: "CONVERTIBLE" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "San Francisco Red",
      transmission: "MANUAL" as const,
      price: 66300,
      quantity: 3,
      description: "382-hp twin-scroll turbo inline-6 roadster equipped with 6-speed manual gearbox and adaptive M chassis.",
      imageUrl: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Mazda",
      model: "MX-5 Miata Club RF",
      category: "CONVERTIBLE" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Soul Red Crystal",
      transmission: "MANUAL" as const,
      price: 40210,
      quantity: 5,
      description: "Pure lightweight sports car with retractable fastback hardtop, Bilstein dampers, and Brembo front brakes.",
      imageUrl: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&auto=format&fit=crop&q=80",
    },

    // 41 - 50: Pickups, Vans & Specialized Vehicles
    {
      make: "Ford",
      model: "F-150 Lightning Platinum",
      category: "PICKUP" as const,
      year: 2024,
      fuelType: "ELECTRIC" as const,
      color: "Star White Metallic",
      transmission: "AUTOMATIC" as const,
      price: 84995,
      quantity: 4,
      description: "580-hp all-electric pickup truck with 9.6 kW Pro Power Onboard home backup generator capability.",
      imageUrl: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Rivian",
      model: "R1T Adventure",
      category: "PICKUP" as const,
      year: 2024,
      fuelType: "ELECTRIC" as const,
      color: "Compass Yellow",
      transmission: "AUTOMATIC" as const,
      price: 79000,
      quantity: 3,
      description: "Quad-motor electric adventure truck delivering 835 hp, 3 feet of water wading, and gear tunnel storage.",
      imageUrl: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "RAM",
      model: "1500 TRX Final Edition",
      category: "PICKUP" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Delmonico Red",
      transmission: "AUTOMATIC" as const,
      price: 117625,
      quantity: 2,
      description: "702-hp supercharged 6.2L HEMI V8 desert truck with Bilstein Black Hawk e2 adaptive shocks.",
      imageUrl: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Chevrolet",
      model: "Silverado EV RST",
      category: "PICKUP" as const,
      year: 2024,
      fuelType: "ELECTRIC" as const,
      color: "Black Metallic",
      transmission: "AUTOMATIC" as const,
      price: 94500,
      quantity: 3,
      description: "754-hp electric truck with 440-mile range, four-wheel steer, and Multi-Flex Midgate cargo pass-through.",
      imageUrl: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "GMC",
      model: "Hummer EV Edition 1",
      category: "PICKUP" as const,
      year: 2024,
      fuelType: "ELECTRIC" as const,
      color: "Interstellar White",
      transmission: "AUTOMATIC" as const,
      price: 106945,
      quantity: 2,
      description: "1,000-horsepower electric supertruck featuring CrabWalk diagonal driving and Watts to Freedom launch mode.",
      imageUrl: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Chrysler",
      model: "Pacifica Pinnacle Hybrid",
      category: "VAN" as const,
      year: 2024,
      fuelType: "HYBRID" as const,
      color: "Ceramic Gray",
      transmission: "AUTOMATIC" as const,
      price: 54050,
      quantity: 4,
      description: "First-class family minivan featuring quilted Nappa leather lumbar pillows and Stow 'n Vac integrated vacuum.",
      imageUrl: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Toyota",
      model: "Sienna Platinum AWD",
      category: "VAN" as const,
      year: 2024,
      fuelType: "HYBRID" as const,
      color: "Sunset Bronze",
      transmission: "AUTOMATIC" as const,
      price: 53405,
      quantity: 5,
      description: "Standard hybrid minivan with electronic AWD capability, 1080p HD rear entertainment, and 36 MPG rating.",
      imageUrl: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Mercedes-Benz",
      model: "Sprinter 2500 Passenger",
      category: "VAN" as const,
      year: 2024,
      fuelType: "DIESEL" as const,
      color: "Arctic White",
      transmission: "AUTOMATIC" as const,
      price: 58800,
      quantity: 3,
      description: "12-passenger executive shuttle van powered by high-output 4-cylinder diesel engine with MBUX touchscreen.",
      imageUrl: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Kia",
      model: "Carnival SX Prestige",
      category: "VAN" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Astra Blue",
      transmission: "AUTOMATIC" as const,
      price: 46300,
      quantity: 5,
      description: "Multi-purpose VIP vehicle with VIP Lounge second-row relaxation seats, leg extensions, and dual sunroofs.",
      imageUrl: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&auto=format&fit=crop&q=80",
    },
    {
      make: "Ford",
      model: "Transit Passenger XLT",
      category: "VAN" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Oxford White",
      transmission: "AUTOMATIC" as const,
      price: 52945,
      quantity: 4,
      description: "15-passenger van powered by 3.5L EcoBoost twin-turbo V6 engine with intelligent All-Wheel Drive system.",
      imageUrl: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&auto=format&fit=crop&q=80",
    },
  ];

  await prisma.vehicle.createMany({
    data: vehiclesData,
  });

  console.log(`Successfully seeded ${vehiclesData.length} authentic vehicle records into PostgreSQL database!`);
}

seed()
  .catch((e) => {
    console.error("Error seeding database:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
