import "dotenv/config";
import { prisma } from "./lib/prisma.js";

async function seed() {
  console.log("Seeding expanded vehicle database for pagination testing...");

  // Clear existing vehicles to re-seed a clean multi-page dataset
  await prisma.purchase.deleteMany();
  await prisma.vehicle.deleteMany();

  const vehiclesData = [
    {
      make: "Toyota",
      model: "Camry LE",
      category: "SEDAN" as const,
      year: 2024,
      fuelType: "HYBRID" as const,
      color: "Silver",
      transmission: "AUTOMATIC" as const,
      price: 28850,
      quantity: 8,
      description: "Fuel-efficient midsize sedan with modern safety features and smooth handling.",
      imageUrl: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&auto=format&fit=crop&q=60",
    },
    {
      make: "Honda",
      model: "CR-V EX-L",
      category: "SUV" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Pearl White",
      transmission: "AUTOMATIC" as const,
      price: 34650,
      quantity: 5,
      description: "Spacious crossover SUV featuring leather interior and intuitive tech infotainment.",
      imageUrl: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&auto=format&fit=crop&q=60",
    },
    {
      make: "Tesla",
      model: "Model 3 Long Range",
      category: "SEDAN" as const,
      year: 2024,
      fuelType: "ELECTRIC" as const,
      color: "Deep Blue",
      transmission: "AUTOMATIC" as const,
      price: 42490,
      quantity: 6,
      description: "All-electric performance sedan with autopilot features and 341-mile battery range.",
      imageUrl: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&auto=format&fit=crop&q=60",
    },
    {
      make: "Ford",
      model: "F-150 Lariat",
      category: "PICKUP" as const,
      year: 2023,
      fuelType: "PETROL" as const,
      color: "Oxford White",
      transmission: "AUTOMATIC" as const,
      price: 57480,
      quantity: 4,
      description: "Rugged full-size pickup truck with impressive towing power and luxury cabin.",
      imageUrl: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&auto=format&fit=crop&q=60",
    },
    {
      make: "BMW",
      model: "330i xDrive",
      category: "SEDAN" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Jet Black",
      transmission: "AUTOMATIC" as const,
      price: 46500,
      quantity: 3,
      description: "Luxury sports sedan delivering turbocharged performance and premium leather seating.",
      imageUrl: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&auto=format&fit=crop&q=60",
    },
    {
      make: "Porsche",
      model: "911 Carrera S",
      category: "COUPE" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Guards Red",
      transmission: "AUTOMATIC" as const,
      price: 131300,
      quantity: 2,
      description: "Iconic rear-engine sports car offering unmatched precision engineering and track performance.",
      imageUrl: "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=800&auto=format&fit=crop&q=60",
    },
    {
      make: "Hyundai",
      model: "Ioniq 5 Limited",
      category: "SUV" as const,
      year: 2024,
      fuelType: "ELECTRIC" as const,
      color: "Matte Gray",
      transmission: "AUTOMATIC" as const,
      price: 53500,
      quantity: 7,
      description: "Futuristic electric CUV with ultra-fast 800V charging capability and panoramic sunroof.",
      imageUrl: "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&auto=format&fit=crop&q=60",
    },
    {
      make: "Chevrolet",
      model: "Corvette Stingray",
      category: "CONVERTIBLE" as const,
      year: 2023,
      fuelType: "PETROL" as const,
      color: "Torch Red",
      transmission: "AUTOMATIC" as const,
      price: 76900,
      quantity: 2,
      description: "Mid-engine V8 supercar capability at an accessible price point with retractable hardtop.",
      imageUrl: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&auto=format&fit=crop&q=60",
    },
    {
      make: "Audi",
      model: "A6 45 TFSI",
      category: "SEDAN" as const,
      year: 2024,
      fuelType: "HYBRID" as const,
      color: "Mythos Black",
      transmission: "AUTOMATIC" as const,
      price: 58100,
      quantity: 5,
      description: "Sophisticated executive sedan equipped with quattro all-wheel drive and dual touchscreens.",
      imageUrl: "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=800&auto=format&fit=crop&q=60",
    },
    {
      make: "Mercedes-Benz",
      model: "GLE 350 4MATIC",
      category: "SUV" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Emerald Green",
      transmission: "AUTOMATIC" as const,
      price: 62650,
      quantity: 4,
      description: "Prestige luxury SUV providing plush air suspension, MBUX AI, and ambient lighting.",
      imageUrl: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&auto=format&fit=crop&q=60",
    },
    {
      make: "Volkswagen",
      model: "Golf GTI Performance",
      category: "HATCHBACK" as const,
      year: 2023,
      fuelType: "PETROL" as const,
      color: "Tornado Red",
      transmission: "MANUAL" as const,
      price: 31995,
      quantity: 6,
      description: "The definitive hot hatch combining agile cornering, manual gearbox, and everyday utility.",
      imageUrl: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800&auto=format&fit=crop&q=60",
    },
    {
      make: "Lexus",
      model: "RX 350h Luxury",
      category: "SUV" as const,
      year: 2024,
      fuelType: "HYBRID" as const,
      color: "Caviar Black",
      transmission: "AUTOMATIC" as const,
      price: 52100,
      quantity: 5,
      description: "Whisper-quiet hybrid crossover boasting Mark Levinson premium audio and ultra-smooth ride.",
      imageUrl: "https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&auto=format&fit=crop&q=60",
    },
    {
      make: "Subaru",
      model: "Outback Touring XT",
      category: "WAGON" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Autumn Green",
      transmission: "AUTOMATIC" as const,
      price: 42795,
      quantity: 6,
      description: "All-weather adventure wagon featuring symmetrical AWD, 8.7 inches of ground clearance, and EyeSight.",
      imageUrl: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&auto=format&fit=crop&q=60",
    },
    {
      make: "Jeep",
      model: "Wrangler Rubicon 4xe",
      category: "SUV" as const,
      year: 2024,
      fuelType: "HYBRID" as const,
      color: "Firecracker Red",
      transmission: "AUTOMATIC" as const,
      price: 61395,
      quantity: 3,
      description: "Trail Rated plug-in hybrid 4x4 capable of electric rock crawling and open-air freedom.",
      imageUrl: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&auto=format&fit=crop&q=60",
    },
    {
      make: "Kia",
      model: "EV6 GT",
      category: "SUV" as const,
      year: 2024,
      fuelType: "ELECTRIC" as const,
      color: "Yacht Blue",
      transmission: "AUTOMATIC" as const,
      price: 61600,
      quantity: 4,
      description: "576-horsepower high-performance electric crossover capable of 0-60 mph in 3.4 seconds.",
      imageUrl: "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&auto=format&fit=crop&q=60",
    },
    {
      make: "Honda",
      model: "Civic Type R",
      category: "HATCHBACK" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Championship White",
      transmission: "MANUAL" as const,
      price: 44795,
      quantity: 2,
      description: "Track-ready hatchback featuring a turbocharged VTEC engine and active aero wing.",
      imageUrl: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800&auto=format&fit=crop&q=60",
    },
    {
      make: "Chrysler",
      model: "Pacificia Pinnacle",
      category: "VAN" as const,
      year: 2024,
      fuelType: "HYBRID" as const,
      color: "Ceramic Gray",
      transmission: "AUTOMATIC" as const,
      price: 54050,
      quantity: 4,
      description: "First-class family minivan featuring quilted Nappa leather seats and FamCAM rear camera.",
      imageUrl: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&auto=format&fit=crop&q=60",
    },
    {
      make: "Toyota",
      model: "Sienna Platinum",
      category: "VAN" as const,
      year: 2024,
      fuelType: "HYBRID" as const,
      color: "Celestial Silver",
      transmission: "AUTOMATIC" as const,
      price: 53405,
      quantity: 5,
      description: "Standard hybrid minivan with AWD capability, super-long-slide second-row captain chairs.",
      imageUrl: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&auto=format&fit=crop&q=60",
    },
    {
      make: "Nissan",
      model: "Z Performance",
      category: "COUPE" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Ikazuchi Yellow",
      transmission: "MANUAL" as const,
      price: 53110,
      quantity: 3,
      description: "400-hp twin-turbo V6 sports coupe honoring retro Z lineage with mechanical limited-slip diff.",
      imageUrl: "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=800&auto=format&fit=crop&q=60",
    },
    {
      make: "Cadillac",
      model: "Escalade ESV Sport",
      category: "SUV" as const,
      year: 2024,
      fuelType: "PETROL" as const,
      color: "Black Raven",
      transmission: "AUTOMATIC" as const,
      price: 109290,
      quantity: 2,
      description: "Full-size luxury flagship SUV featuring 38-inch curved OLED screen and AKG 36-speaker sound system.",
      imageUrl: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&auto=format&fit=crop&q=60",
    },
  ];

  await prisma.vehicle.createMany({
    data: vehiclesData,
  });

  console.log(`Successfully seeded ${vehiclesData.length} vehicles into the database across multiple pages!`);
}

seed()
  .catch((e) => {
    console.error("Error seeding database:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
